name: Set default branch for GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  set-default-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set default branch
        run: |
          echo "Default branch for GitHub Pages" > .git/refs/heads/main
        shell: bash
